### ISSUE TITLE
Blog Comment service - review comments

### ISSUE THREAD

**Issue by RajPack** [csindhe/Angular4AppDevelopment#1]
# Regarding the below file.
### Angular4AppDevelopment/blog-demo/src/app/service/blog-service.ts

The idea of using parent id to store comment reply is great. There are couple of things that can be improved  in this file,

1.  We don't need a separate fetch for a blog comment and blog reply comment, since both are essentially a comment type object.. `blogComm.blogId === blogId && blogComm.parentId === undefined` the later part of this condition is not needed. It only invites for the need to fetch comment replies separately. .

-  To effectively do this - simply fetch all the comments of an input blog in `getCommentBlog(blogId: any)` function in an observable and use `map` operator to generate another observable - which will transform the list the comments into list of hierarchical comments..  :) You can do this by creating another function that will take a list of comments of a blog and then traverse each one and place reply comments in `children` member of type `array<blogComment>` (say a new member of comments obj) of the blog comment object.. 
- And as far as the UI is concerned use `*ngFor` within another `*ngFor` for displaying reply comments (reply comments - `children` array) to a parent blog comment... 

2. I noticed there are new Observables and subscriptions created inside functions - these don't die gracefully but may introduce memory leaks. You may want to either unsubscribe things before the end of the function or point these observables to private members of the class..

**Comment by csindhe** [comment]
To effectively do this - simply fetch all the comments of an input blog in getCommentBlog(blogId: any) function in an observable and use map operator to generate another observable - which will transform the list the comments into list of hierarchical comments.. :) You can do this by creating another function that will take a list of comments of a blog and then traverse each one and place reply comments in children member of type array<blogComment> (say a new member of comments obj) of the blog comment object..
And as far as the UI is concerned use *ngFor within another *ngFor for displaying reply comments (reply comments - children array) to a parent blog comment...

-- You mean to say there was no need for a separate component for Comment Reply??

**Comment by RajPack** [comment]
no need for a separate component.. as far as replies are concerned, they are just comments with a parent !!

**Comment by csindhe** [comment]
correct .. rectifying the code now :)

**Comment by RajPack** [comment]
awesome!!

**Comment by csindhe** [comment]
Implemented the recommended changes. working fine now. Thanks
